// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/google/wire"
	"zmall/server/user"
)

// Injectors from wire.go:

func NewApp() *App {
	db := InitDB()
	module := user.NewModule(db)
	userHandler := module.Hdl
	engine := InitWebServer(userHandler)
	app := &App{
		Server: engine,
	}
	return app
}

// wire.go:

var BaseSet = wire.NewSet(InitDB)
